name: lc-ssj
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.12
  - numpy
  - numba
  - pip
  - ipykernel
  # linting
  - black
  - isort
  - pip:
    - sequence-jacobian==1.0.0
    - econ-ark==0.16.0